/* Generated by cbindgen — do not edit manually */

#ifndef SECURITY_CORE_H
#define SECURITY_CORE_H

/* Warning: this file is autogenerated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * FFI-safe intent analysis result.
 */
typedef struct IntentResultFFI {
    bool is_threat;
    int8_t severity;
    uint8_t layers_fired;
    uint32_t score;
    bool l1;
    bool l2;
    bool l3;
    bool l4;
    bool l5;
    bool l6;
    char *label;
    char *confidence;
} IntentResultFFI;

/**
 * FFI-safe single finding.
 */
typedef struct FindingFFI {
    char *finding_type;
    char *label;
    int8_t severity;
    char *category;
    char *source;
    char *match_preview;
    uint32_t offset;
} FindingFFI;

/**
 * FFI-safe findings array.
 */
typedef struct FindingsArrayFFI {
    struct FindingFFI *items;
    uint32_t count;
} FindingsArrayFFI;

/**
 * FFI-safe validation result.
 */
typedef struct ValidationResultFFI {
    bool safe;
    char *reason;
    int8_t severity;
    char *category;
} ValidationResultFFI;

/**
 * FFI-safe sanitization result.
 */
typedef struct SanitizationResultFFI {
    char *sanitized;
    bool modified;
    char *changes_json;
} SanitizationResultFFI;

/**
 * FFI-safe single threat.
 */
typedef struct ThreatFFI {
    char *threat_type;
    char *label;
    int8_t severity;
    char *category;
} ThreatFFI;

/**
 * FFI-safe threats array (for file/email/message scanning).
 */
typedef struct ThreatsArrayFFI {
    struct ThreatFFI *items;
    uint32_t count;
} ThreatsArrayFFI;

/**
 * FFI-safe whitelist scan policy.
 */
typedef struct ScanPolicyFFI {
    bool is_whitelisted;
} ScanPolicyFFI;

/**
 * FFI-safe vault operation result.
 */
typedef struct VaultResultFFI {
    bool success;
    char *message;
    uint32_t entries_affected;
} VaultResultFFI;

/**
 * FFI-safe vault entry.
 */
typedef struct VaultEntryFFI {
    char *original_path;
    char *vault_path;
    uint8_t protection;
    char *encrypted_at;
    uint64_t size_bytes;
    bool is_directory;
    bool is_unlocked;
} VaultEntryFFI;

/**
 * FFI-safe vault entry array.
 */
typedef struct VaultEntryArrayFFI {
    struct VaultEntryFFI *items;
    uint32_t count;
} VaultEntryArrayFFI;

/**
 * Progress callback type for batch vault operations.
 * Returns true to continue, false to cancel.
 */
typedef bool (*VaultProgressCallback)(uint32_t current,
                                      uint32_t total,
                                      const char *current_path,
                                      void *user_data);

/**
 * Initialize with an optional config path. Returns true on success.
 */
bool sec_init(const char *configPath);

/**
 * 7-layer intent analysis. Caller must free with sec_free_intent_result.
 */
struct IntentResultFFI *sec_parse_intent(const char *text, uint8_t channel);

/**
 * Scan text for sensitive data. Caller must free with sec_free_findings.
 */
struct FindingsArrayFFI *sec_scan_sensitive_data(const char *text, const char *source);

/**
 * Validate text for prompt injection. Caller must free with sec_free_validation_result.
 */
struct ValidationResultFFI *sec_validate_prompt(const char *text, const char *source);

/**
 * Sanitize text. Caller must free with sec_free_sanitization_result.
 */
struct SanitizationResultFFI *sec_sanitize_text(const char *text);

/**
 * Scan file content for threats. Caller must free with sec_free_threats.
 */
struct ThreatsArrayFFI *sec_scan_file_content(const char *text);

/**
 * Analyze email text for threats. Caller must free with sec_free_threats.
 */
struct ThreatsArrayFFI *sec_analyze_email(const char *text);

/**
 * Analyze message text for threats. Caller must free with sec_free_threats.
 */
struct ThreatsArrayFFI *sec_analyze_message(const char *text);

/**
 * Check scan policy. Always returns a valid pointer. Free with sec_free_scan_policy.
 */
struct ScanPolicyFFI *sec_whitelist_check(const char *sender);

void sec_free_intent_result(struct IntentResultFFI *ptr);

void sec_free_findings(struct FindingsArrayFFI *ptr);

void sec_free_validation_result(struct ValidationResultFFI *ptr);

void sec_free_sanitization_result(struct SanitizationResultFFI *ptr);

void sec_free_threats(struct ThreatsArrayFFI *ptr);

void sec_free_scan_policy(struct ScanPolicyFFI *ptr);

/**
 * Check if vault has been set up.
 */
bool sec_vault_is_setup(const char *securityDir);

/**
 * First-time vault setup — generates salt, creates manifest, writes recovery file.
 */
struct VaultResultFFI *sec_vault_setup(const char *securityDir);

/**
 * Set the initial vault passphrase (first-time only).
 */
bool sec_vault_set_passphrase(const char *securityDir, const char *passphrase);

/**
 * Verify vault passphrase.
 */
bool sec_vault_verify_passphrase(const char *securityDir, const char *passphrase);

/**
 * Add files to vault. `paths` is a colon-separated list. `protection`: 0=locked, 1=read_only, 2=local_only, 3=read_only_local, 4=locked_local.
 */
struct VaultResultFFI *sec_vault_add(const char *securityDir,
                                     const char *paths,
                                     uint8_t protection,
                                     const char *passphrase);

/**
 * Unlock (decrypt) vault entries. `paths` is colon-separated.
 */
struct VaultResultFFI *sec_vault_unlock(const char *securityDir,
                                        const char *paths,
                                        const char *passphrase);

/**
 * Lock (re-encrypt) previously unlocked entries. `paths` is colon-separated.
 */
struct VaultResultFFI *sec_vault_lock(const char *securityDir,
                                      const char *paths,
                                      const char *passphrase);

/**
 * Remove entries from vault (decrypt and restore). `paths` is colon-separated.
 */
struct VaultResultFFI *sec_vault_remove(const char *securityDir,
                                        const char *paths,
                                        const char *passphrase);

/**
 * List all vault entries.
 */
struct VaultEntryArrayFFI *sec_vault_list(const char *securityDir, const char *passphrase);

/**
 * Change vault passphrase.
 */
struct VaultResultFFI *sec_vault_change_passphrase(const char *securityDir,
                                                   const char *oldPassphrase,
                                                   const char *newPassphrase);

/**
 * Change protection level of vault entries. `paths` is newline-separated.
 * `new_protection`: 0=locked, 1=read_only, 2=local_only, 3=read_only_local, 4=locked_local.
 */
struct VaultResultFFI *sec_vault_change_protection(const char *securityDir,
                                                   const char *paths,
                                                   uint8_t newProtection,
                                                   const char *passphrase);

/**
 * Toggle local-only monitoring on vault entries. `paths` is newline-separated.
 */
struct VaultResultFFI *sec_vault_toggle_local_only(const char *securityDir,
                                                   const char *paths,
                                                   const char *passphrase);

/**
 * Add files to vault with progress callback and cancellation support.
 * `paths` is newline-separated.
 */
struct VaultResultFFI *sec_vault_add_with_progress(const char *securityDir,
                                                   const char *paths,
                                                   uint8_t protection,
                                                   const char *passphrase,
                                                   VaultProgressCallback callback,
                                                   void *userData);

/**
 * Update a vault entry's path after a file move.
 */
struct VaultResultFFI *sec_vault_update_path(const char *securityDir,
                                             const char *oldPath,
                                             const char *newPath,
                                             const char *passphrase);

/**
 * Free a VaultResultFFI.
 */
void sec_free_vault_result(struct VaultResultFFI *ptr);

/**
 * Free a VaultEntryArrayFFI.
 */
void sec_free_vault_entries(struct VaultEntryArrayFFI *ptr);

/**
 * Get the current protection tier from config. Returns 0=relaxed, 1=balanced, 2=strict.
 * Returns -1 on error.
 */
int8_t sec_get_protection_tier(const char *configPath);

/**
 * Set the protection tier in config.toml. tier: 0=relaxed, 1=balanced, 2=strict.
 * Returns true on success.
 */
bool sec_set_protection_tier(const char *configPath, int8_t tier);

/**
 * Get the fully resolved effective security config as a JSON string.
 * Caller must free with sec_free_string.
 */
char *sec_get_effective_config(const char *configPath);

/**
 * Free a string returned by sec_get_effective_config.
 */
void sec_free_string(char *ptr);

#endif  /* SECURITY_CORE_H */
