/* Generated by cbindgen — do not edit manually */

#ifndef SECURITY_CORE_H
#define SECURITY_CORE_H

/* Warning: this file is autogenerated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * FFI-safe intent analysis result.
 */
typedef struct IntentResultFFI {
    bool is_threat;
    int8_t severity;
    uint8_t layers_fired;
    uint32_t score;
    bool l1;
    bool l2;
    bool l3;
    bool l4;
    bool l5;
    bool l6;
    char *label;
    char *confidence;
} IntentResultFFI;

/**
 * FFI-safe single finding.
 */
typedef struct FindingFFI {
    char *finding_type;
    char *label;
    int8_t severity;
    char *category;
    char *source;
    char *match_preview;
    uint32_t offset;
} FindingFFI;

/**
 * FFI-safe findings array.
 */
typedef struct FindingsArrayFFI {
    struct FindingFFI *items;
    uint32_t count;
} FindingsArrayFFI;

/**
 * FFI-safe validation result.
 */
typedef struct ValidationResultFFI {
    bool safe;
    char *reason;
    int8_t severity;
    char *category;
} ValidationResultFFI;

/**
 * FFI-safe sanitization result.
 */
typedef struct SanitizationResultFFI {
    char *sanitized;
    bool modified;
    char *changes_json;
} SanitizationResultFFI;

/**
 * FFI-safe single threat.
 */
typedef struct ThreatFFI {
    char *threat_type;
    char *label;
    int8_t severity;
    char *category;
} ThreatFFI;

/**
 * FFI-safe threats array (for file/email/message scanning).
 */
typedef struct ThreatsArrayFFI {
    struct ThreatFFI *items;
    uint32_t count;
} ThreatsArrayFFI;

/**
 * FFI-safe whitelist scan policy.
 */
typedef struct ScanPolicyFFI {
    bool is_whitelisted;
} ScanPolicyFFI;

/**
 * FFI-safe vault operation result.
 */
typedef struct VaultResultFFI {
    bool success;
    char *message;
    uint32_t entries_affected;
} VaultResultFFI;

/**
 * FFI-safe vault entry.
 */
typedef struct VaultEntryFFI {
    char *original_path;
    char *vault_path;
    uint8_t protection;
    char *encrypted_at;
    uint64_t size_bytes;
    bool is_directory;
    bool is_unlocked;
} VaultEntryFFI;

/**
 * FFI-safe vault entry array.
 */
typedef struct VaultEntryArrayFFI {
    struct VaultEntryFFI *items;
    uint32_t count;
} VaultEntryArrayFFI;

/**
 * Progress callback type for batch vault operations.
 * Returns true to continue, false to cancel.
 */
typedef bool (*VaultProgressCallback)(uint32_t current,
                                      uint32_t total,
                                      const char *current_path,
                                      void *user_data);

/**
 * FFI-safe command check result.
 */
typedef struct CommandCheckResultFFI {
    int8_t decision;
    char *reason;
    char *matched_rule;
} CommandCheckResultFFI;

/**
 * FFI-safe feed check result.
 */
typedef struct FeedCheckResultFFI {
    int8_t threat_level;
    char *feed_name;
    char *indicator;
} FeedCheckResultFFI;

/**
 * FFI-safe package check result.
 */
typedef struct PackageCheckResultFFI {
    bool vulnerable;
    int8_t severity;
    char *cve;
    char *source;
} PackageCheckResultFFI;

/**
 * FFI-safe start result.
 */
typedef struct LocalServicesStartResult {
    /**
     * True if the listener is now running (including the case where it was
     * already running from a prior call).
     */
    bool ok;
    /**
     * The bound address as returned by the OS. Useful when the caller
     * passed port 0. Null on failure. Caller must free with `sec_free_string`.
     */
    char *bound_addr;
} LocalServicesStartResult;

/**
 * Initialize with an optional config path. Returns true on success.
 */
bool sec_init(const char *configPath);

/**
 * 7-layer intent analysis. Caller must free with sec_free_intent_result.
 */
struct IntentResultFFI *sec_parse_intent(const char *text, uint8_t channel);

/**
 * Scan text for sensitive data. Caller must free with sec_free_findings.
 */
struct FindingsArrayFFI *sec_scan_sensitive_data(const char *text, const char *source);

/**
 * Validate text for prompt injection. Caller must free with sec_free_validation_result.
 */
struct ValidationResultFFI *sec_validate_prompt(const char *text, const char *source);

/**
 * Sanitize text. Caller must free with sec_free_sanitization_result.
 */
struct SanitizationResultFFI *sec_sanitize_text(const char *text);

/**
 * Scan file content for threats. Caller must free with sec_free_threats.
 */
struct ThreatsArrayFFI *sec_scan_file_content(const char *text);

/**
 * Analyze an attachment's leading bytes vs. its filename for a disguised executable (magic-byte
 * true-type check). `prefix`/`len` describe a byte buffer (a small prefix is sufficient). Caller
 * must free with sec_free_threats.
 */
struct ThreatsArrayFFI *sec_analyze_attachment_structure(const uint8_t *prefix,
                                                         uintptr_t len,
                                                         const char *filename);

/**
 * Inspect a container attachment (Office OOXML doc or ZIP archive) for a disguised macro document,
 * dangerous archive contents, or an encrypted archive — by reading ZIP entry metadata only (no
 * decompression). `prefix`/`len` describe a byte buffer (a bounded prefix is sufficient). Caller
 * must free with sec_free_threats.
 */
struct ThreatsArrayFFI *sec_analyze_container(const uint8_t *prefix,
                                              uintptr_t len,
                                              const char *filename);

/**
 * Analyze email text for threats. Caller must free with sec_free_threats.
 */
struct ThreatsArrayFFI *sec_analyze_email(const char *text);

/**
 * Analyze message text for threats. Caller must free with sec_free_threats.
 */
struct ThreatsArrayFFI *sec_analyze_message(const char *text);

/**
 * Check scan policy. Always returns a valid pointer. Free with sec_free_scan_policy.
 */
struct ScanPolicyFFI *sec_whitelist_check(const char *sender);

void sec_free_intent_result(struct IntentResultFFI *ptr);

void sec_free_findings(struct FindingsArrayFFI *ptr);

void sec_free_validation_result(struct ValidationResultFFI *ptr);

void sec_free_sanitization_result(struct SanitizationResultFFI *ptr);

void sec_free_threats(struct ThreatsArrayFFI *ptr);

void sec_free_scan_policy(struct ScanPolicyFFI *ptr);

/**
 * Check if vault has been set up.
 */
bool sec_vault_is_setup(const char *securityDir);

/**
 * First-time vault setup — generates salt, creates manifest, writes recovery file.
 */
struct VaultResultFFI *sec_vault_setup(const char *securityDir);

/**
 * Set the initial vault passphrase (first-time only).
 */
bool sec_vault_set_passphrase(const char *securityDir, const char *passphrase);

/**
 * Verify vault passphrase.
 */
bool sec_vault_verify_passphrase(const char *securityDir, const char *passphrase);

/**
 * Add files to vault. `paths` is a colon-separated list. `protection`: 0=locked, 1=read_only, 2=local_only, 3=read_only_local, 4=locked_local.
 */
struct VaultResultFFI *sec_vault_add(const char *securityDir,
                                     const char *paths,
                                     uint8_t protection,
                                     const char *passphrase);

/**
 * Unlock (decrypt) vault entries. `paths` is colon-separated.
 */
struct VaultResultFFI *sec_vault_unlock(const char *securityDir,
                                        const char *paths,
                                        const char *passphrase);

/**
 * Lock (re-encrypt) previously unlocked entries. `paths` is colon-separated.
 */
struct VaultResultFFI *sec_vault_lock(const char *securityDir,
                                      const char *paths,
                                      const char *passphrase);

/**
 * Remove entries from vault (decrypt and restore). `paths` is colon-separated.
 */
struct VaultResultFFI *sec_vault_remove(const char *securityDir,
                                        const char *paths,
                                        const char *passphrase);

/**
 * List all vault entries.
 */
struct VaultEntryArrayFFI *sec_vault_list(const char *securityDir, const char *passphrase);

/**
 * Change vault passphrase.
 */
struct VaultResultFFI *sec_vault_change_passphrase(const char *securityDir,
                                                   const char *oldPassphrase,
                                                   const char *newPassphrase);

/**
 * Change protection level of vault entries. `paths` is newline-separated.
 * `new_protection`: 0=locked, 1=read_only, 2=local_only, 3=read_only_local, 4=locked_local.
 */
struct VaultResultFFI *sec_vault_change_protection(const char *securityDir,
                                                   const char *paths,
                                                   uint8_t newProtection,
                                                   const char *passphrase);

/**
 * Toggle local-only monitoring on vault entries. `paths` is newline-separated.
 */
struct VaultResultFFI *sec_vault_toggle_local_only(const char *securityDir,
                                                   const char *paths,
                                                   const char *passphrase);

/**
 * Add files to vault with progress callback and cancellation support.
 * `paths` is newline-separated.
 */
struct VaultResultFFI *sec_vault_add_with_progress(const char *securityDir,
                                                   const char *paths,
                                                   uint8_t protection,
                                                   const char *passphrase,
                                                   VaultProgressCallback callback,
                                                   void *userData);

/**
 * Update a vault entry's path after a file move.
 */
struct VaultResultFFI *sec_vault_update_path(const char *securityDir,
                                             const char *oldPath,
                                             const char *newPath,
                                             const char *passphrase);

/**
 * Free a VaultResultFFI.
 */
void sec_free_vault_result(struct VaultResultFFI *ptr);

/**
 * Free a VaultEntryArrayFFI.
 */
void sec_free_vault_entries(struct VaultEntryArrayFFI *ptr);

/**
 * Install the process-global master key. `hex` must be the hex encoding of
 * exactly 32 random bytes sourced from the macOS Keychain.
 * Returns true on success. Once set, subsequent calls are no-ops (idempotent).
 */
bool sec_set_master_key(const char *hex);

/**
 * True iff the master key has already been installed.
 */
bool sec_has_master_key(void);

/**
 * Encrypt a JSON string with the WHITELIST AAD tag. Returns hex string.
 * Caller must free with sec_free_string.
 * Returns null if the master key has not been installed — callers must NOT
 * fall back to plaintext storage.
 */
char *sec_encrypt_whitelist(const char *json);

/**
 * Decrypt a hex string with the WHITELIST AAD tag. Returns JSON string.
 * Caller must free with sec_free_string.
 */
char *sec_decrypt_whitelist(const char *hex);

/**
 * ONE-SHOT MIGRATION ONLY: decrypt a whitelist blob that was encrypted with
 * the legacy default-passphrase key (pre-master-key versions of the app).
 * Swift calls this when normal decryption fails, then re-encrypts with the
 * new master key. Will be removed in a future version.
 */
char *sec_decrypt_whitelist_legacy(const char *hex);

/**
 * Check a command against the policy. Caller must free with sec_free_command_check.
 */
struct CommandCheckResultFFI *sec_command_check(const char *command, const char *configPath);

/**
 * Free a CommandCheckResultFFI.
 */
void sec_free_command_check(struct CommandCheckResultFFI *ptr);

/**
 * Verify all tracked model files. Returns JSON array of results.
 * Uses effective paths: discovered + default + user-configured.
 * Caller must free with sec_free_string.
 */
char *sec_model_verify(const char *securityDir);

/**
 * Discover model directories by scanning home + /Volumes/.
 * Returns JSON array of directory paths. Caller must free with sec_free_string.
 */
char *sec_model_discover_dirs(const char *securityDir);

/**
 * Scan for model files and return JSON array of discovered paths.
 * Caller must free with sec_free_string.
 */
char *sec_model_scan(const char *securityDir);

/**
 * Log a policy decision. entry_json is a JSON string of PolicyDecision.
 * Returns true on success.
 */
bool sec_audit_log(const char *securityDir, const char *entryJson);

/**
 * Initialize threat feeds database. Call once at startup.
 */
bool sec_feed_init(const char *securityDir);

/**
 * Check a URL against threat feeds. Caller must free with sec_free_feed_check.
 */
struct FeedCheckResultFFI *sec_feed_check_url(const char *url);

/**
 * Check a domain against threat feeds. Caller must free with sec_free_feed_check.
 */
struct FeedCheckResultFFI *sec_feed_check_domain(const char *domain);

/**
 * Refresh all threat feeds. Returns count of entries refreshed, -1 on error.
 * BLOCKING — call from a background thread.
 */
int32_t sec_feed_refresh(void);

/**
 * Get feed stats as JSON string. Caller must free with sec_free_string.
 */
char *sec_feed_stats(void);

/**
 * Get total entries count across all feeds.
 */
uint32_t sec_feed_total_entries(void);

/**
 * Free a FeedCheckResultFFI.
 */
void sec_free_feed_check(struct FeedCheckResultFFI *ptr);

/**
 * Initialize the package-vulns SQLite cache. Call once at startup.
 */
bool sec_package_vulns_init(const char *securityDir);

/**
 * Check a single package against OSV (cache-first). BLOCKING — on cache
 * miss makes an HTTP call up to 30 s. Call from a background thread.
 */
struct PackageCheckResultFFI *sec_check_package(const char *ecosystem,
                                                const char *name,
                                                const char *version);

/**
 * Batch-check N packages. `queries_json` is a JSON array:
 * `[{"ecosystem":"PyPI","name":"litellm","version":"1.82.8"}, ...]`
 * Returns JSON array of results. Caller frees with `sec_free_string`.
 * BLOCKING — makes one OSV /querybatch call on cache miss.
 */
char *sec_check_package_batch(const char *queriesJson);

/**
 * Free a `PackageCheckResultFFI`.
 */
void sec_free_package_check(struct PackageCheckResultFFI *ptr);

/**
 * Get the current protection tier from config. Returns 0=relaxed, 1=balanced, 2=strict.
 * Returns -1 on error.
 */
int8_t sec_get_protection_tier(const char *configPath);

/**
 * Set the protection tier in config.toml. tier: 0=relaxed, 1=balanced, 2=strict.
 * Returns true on success.
 */
bool sec_set_protection_tier(const char *configPath, int8_t tier);

/**
 * Get the fully resolved effective security config as a JSON string.
 * Caller must free with sec_free_string.
 */
char *sec_get_effective_config(const char *configPath);

/**
 * Free a string returned by sec_get_effective_config.
 */
void sec_free_string(char *ptr);

/**
 * Start the in-process HTTP listener that serves:
 *   - POST /privacy/evaluate
 *   - POST /intent/verify
 *   - GET  /health
 *
 * Parameters:
 *   - `bind_addr`       : e.g. "127.0.0.1:7459". `127.0.0.1:0` picks a free port.
 *   - `config_path`     : optional; null uses defaults.
 *   - `audit_log_path`  : optional; null disables audit logging.
 *
 * Returns a heap-allocated `LocalServicesStartResult`. Caller must free via
 * `sec_free_local_services_start_result`. The listener runs on a detached
 * thread — it lives for the life of the process.
 */
struct LocalServicesStartResult *sec_local_services_start(const char *bindAddr,
                                                          const char *configPath,
                                                          const char *auditLogPath);

/**
 * True iff the listener is currently running in this process.
 */
bool sec_local_services_is_running(void);

/**
 * Free the result struct returned by `sec_local_services_start`.
 */
void sec_free_local_services_start_result(struct LocalServicesStartResult *ptr);

#endif  /* SECURITY_CORE_H */
