/* Generated by cbindgen — do not edit manually */

#ifndef SECURITY_CORE_H
#define SECURITY_CORE_H

/* Warning: this file is autogenerated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * FFI-safe intent analysis result.
 */
typedef struct IntentResultFFI {
    bool is_threat;
    int8_t severity;
    uint8_t layers_fired;
    bool l1;
    bool l2;
    bool l3;
    bool l4;
    bool l5;
    bool l6;
    char *label;
    char *confidence;
} IntentResultFFI;

/**
 * FFI-safe single finding.
 */
typedef struct FindingFFI {
    char *finding_type;
    char *label;
    int8_t severity;
    char *category;
    char *source;
    char *match_preview;
    uint32_t offset;
} FindingFFI;

/**
 * FFI-safe findings array.
 */
typedef struct FindingsArrayFFI {
    struct FindingFFI *items;
    uint32_t count;
} FindingsArrayFFI;

/**
 * FFI-safe validation result.
 */
typedef struct ValidationResultFFI {
    bool safe;
    char *reason;
    int8_t severity;
    char *category;
} ValidationResultFFI;

/**
 * FFI-safe sanitization result.
 */
typedef struct SanitizationResultFFI {
    char *sanitized;
    bool modified;
    char *changes_json;
} SanitizationResultFFI;

/**
 * FFI-safe single threat.
 */
typedef struct ThreatFFI {
    char *threat_type;
    char *label;
    int8_t severity;
    char *category;
} ThreatFFI;

/**
 * FFI-safe threats array (for file/email/message scanning).
 */
typedef struct ThreatsArrayFFI {
    struct ThreatFFI *items;
    uint32_t count;
} ThreatsArrayFFI;

/**
 * FFI-safe whitelist scan policy.
 */
typedef struct ScanPolicyFFI {
    bool is_whitelisted;
} ScanPolicyFFI;

/**
 * Initialize with an optional config path. Returns true on success.
 */
bool sec_init(const char *configPath);

/**
 * 7-layer intent analysis. Caller must free with sec_free_intent_result.
 */
struct IntentResultFFI *sec_parse_intent(const char *text, uint8_t channel);

/**
 * Scan text for sensitive data. Caller must free with sec_free_findings.
 */
struct FindingsArrayFFI *sec_scan_sensitive_data(const char *text, const char *source);

/**
 * Validate text for prompt injection. Caller must free with sec_free_validation_result.
 */
struct ValidationResultFFI *sec_validate_prompt(const char *text, const char *source);

/**
 * Sanitize text. Caller must free with sec_free_sanitization_result.
 */
struct SanitizationResultFFI *sec_sanitize_text(const char *text);

/**
 * Scan file content for threats. Caller must free with sec_free_threats.
 */
struct ThreatsArrayFFI *sec_scan_file_content(const char *text);

/**
 * Analyze email text for threats. Caller must free with sec_free_threats.
 */
struct ThreatsArrayFFI *sec_analyze_email(const char *text);

/**
 * Analyze message text for threats. Caller must free with sec_free_threats.
 */
struct ThreatsArrayFFI *sec_analyze_message(const char *text);

/**
 * Check scan policy. Always returns a valid pointer. Free with sec_free_scan_policy.
 */
struct ScanPolicyFFI *sec_whitelist_check(const char *sender);

void sec_free_intent_result(struct IntentResultFFI *ptr);

void sec_free_findings(struct FindingsArrayFFI *ptr);

void sec_free_validation_result(struct ValidationResultFFI *ptr);

void sec_free_sanitization_result(struct SanitizationResultFFI *ptr);

void sec_free_threats(struct ThreatsArrayFFI *ptr);

void sec_free_scan_policy(struct ScanPolicyFFI *ptr);

#endif  /* SECURITY_CORE_H */
